### ISSUE TITLE
Hi, Can I have a copy of your thesis

### ISSUE THREAD

**Issue by Akhilnandh** [Barbale98/Enhanced_NSGA-II_EFJSP-TT#1]
Hi, Can I have a copy of your thesis for my reference.

**Comment by Barbale98** [comment]
Sure you can find it at this link: https://www.researchgate.net/publication/382329155_Enhanced_Genetic_Algorithm_to_Solve_the_Energy-efficient_Flexible_Job_Shop_Scheduling_Problem
